version: '3.5'
services:
  podkit_frontend:
    build: .
    restart: always
    ports:
      - "3001:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"